#!/usr/bin/env node
// Regenerates seed.sql from the sector counts below.
//
// This is the ONE place to edit once you know the real numbers.
// Edit SECTOR_COUNTS, then run: node db/generate-seed.js
// It rewrites db/seed.sql, which the deploy step (or `npm run db:seed`) loads into D1.
//
// The mock numbers below match the 140 booths already laid out in the
// current venue (from the DEV21 performance report): 30 Manufacturing,
// 30 Health Science, 30 Agribusiness, 30 Construction, 20 Information
// Technology. Replace with real employer-signup counts per sector whenever
// you have them -- nothing else in the system needs to change.
const SECTOR_COUNTS = {
  'Manufacturing': 30,
  'Health Science': 30,
  'Agribusiness': 30,
  'Construction': 30,
  'Information Technology': 20,
};

const fs = require('fs');
const path = require('path');

const lines = [
  '-- Generated by db/generate-seed.js -- do not hand-edit, edit SECTOR_COUNTS instead.',
  'DELETE FROM slots;',
];

let total = 0;
for (const [sector, count] of Object.entries(SECTOR_COUNTS)) {
  const values = [];
  for (let n = 1; n <= count; n++) {
    values.push(`('${sector.replace(/'/g, "''")}', ${n}, 'open')`);
    total++;
  }
  lines.push(`INSERT INTO slots (sector, slot_number, status) VALUES\n  ${values.join(',\n  ')};`);
}

const out = path.join(__dirname, 'seed.sql');
fs.writeFileSync(out, lines.join('\n\n') + '\n');
console.log(`Wrote ${out} with ${total} slots across ${Object.keys(SECTOR_COUNTS).length} sectors.`);
